GET http://localhost:8080/market

###

GET http://localhost:8080/market/BTC

###

POST http://localhost:8080/user
Accept: application/json
Content-type: application/json

{
  "userId": "user2"
}

###
GET http://localhost:8080/user/user2
Accept: application/json
Content-type: application/json


###
POST http://localhost:8080/quote
Accept: application/json
Content-type: application/json

{
  "userId": "user2",
  "fromCurrency": "EUR",
  "toCurrency": "BTC",
  "amount": "0.01"
}

> {%
  client.global.set("quoteId", response.body.id);
%}

###

###
POST http://localhost:8080/order
Accept: application/json
Content-type: application/json

{
  "userId": "user2",
  "quoteId": "{{quoteId}}"
}


###